### ISSUE TITLE
Refactor dependencies

### ISSUE THREAD

**Issue by ChrisSchinnerl** [NebulousLabs/writeaheadlog#37]
- Dependency interfaces and the production dependencies should be located in `dependency.go`
- Other dependencies should be in `dependency_test.go`
- Each dependency should have a name starting with a lowercase "dependency" like `dependencyCommitFail`

**Comment by DavidVorick** [comment]
Looks good to me.

**Comment by DavidVorick** [comment]
I'm going to leave this issue open for a community member to tackle as an easy beginner contribution.
