### ISSUE TITLE
Inconsistency in Transaction.append

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/writeaheadlog#45]
The `append` method behaves inconsistently, both when new pages need to be allocated, and when they don't.

When no new pages are needed, `append` appends the extra marshalled data to the last page's `payload`. It then returns immediately, without actually writing the new payload to disk or appending the new updates to `t.Updates`. This branch should be modified to write the new data. Also, the original payload and old `t.Updates` should be preserved if the write fails.

When new pages are needed, `append` reserves them from the WAL, writes them to disk, then writes the former last page to disk (completing the chain), and then appends the new updates to `t.Updates`. This branch is almost correct, but should be modified to preserve the last page's `payload` and `nextPage` fields if the writes fail.

I'm currently refactoring code that touches `append`, so we should hold off on fixing this until we've merged that. In the meantime, we should write a regression test that demonstrates the inconsistency.

**Comment by ChrisSchinnerl** [comment]
In addition to preserving the original payload and old `t.Updates` we should also reset the former last page's `nextPage` by setting it to `nil` again.
