### ISSUE TITLE
Remove Version field from Update

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/writeaheadlog#59]
The `Version` field adds at least 8 bytes of overhead, and it's not clear that it adds much value to the user. If users do need a versioning scheme, they can easily append it to the `Name` field.

**Comment by ChrisSchinnerl** [comment]
I'm also not too sure about the `Name`. Both could be fields in the payload in my opinion. Might be more efficient to just add 1 byte to the instructions than having to marshal a string every time.
